repository: 'https://github.com/astroconda/astroconda-etc'
channels:
  - 'http://ssb.stsci.edu/astroconda'
numpy_version: 1.11
packages:
  - pandeia-thirdparty
  - pyetc-thirdparty
  - ext_shmht
  - django
  - epydoc
  - linecache2
  - mechanize
  - parsley
  - pmw
  - pyfits
  - sphinx-bootstrap-theme
  - sphinx_rtd_theme
  - threading2
  - traceback2
  - urwid
  - websocket-client
  - ws4py
  - wsgiref
  - yolk

