repository: 'https://github.com/astroconda/astroconda-contrib'
channel_URL: 'http://ssb.stsci.edu/astroconda'
numpy_version: 1.11
packages:
  - stsci.tools
  - stsci.imagestats
  - stsci-data-analysis
  - stsci-hst
  - stsci

  - verhawk
  - acstools
  - appdirs
  - aprio
  - asdf-standard
  - asdf
  - astroimtools
  - asv
  - calcos
  - cfitsio
  - costools
  - crds
  - d2to1
  - drizzle
  - drizzlepac
  - ds9
  - fftw
  - fitsblender
  - fitsverify
  - ginga
  - glueviz
  - glue-core
  - glue-vispy-viewers
  - glue-ginga
  - gwcs
  - hstcal
  - htc_utils
  - imexam
  - jwst_coronagraph_visibility
  - jwst_gtvt
  - jwxml
  - mosviz
  - nictools
  - opuscoords
#  - pandokia
  - photutils
  - poppy
  - purge_path
  - pyds9
  - pyfftw
  - pyobjc-core
  - pyobjc-framework-cocoa
  - pyobjc-framework-quartz
  - pyqtgraph
  - pyraf
  - pyregion
  - pysynphot
  - python-daemon
  - pytools
  - pywcs
  - reftools
  - relic
  - selenium
  - shunit2
  - specviz
  - specutils
  - sphere
  - sphinx_rtd_theme
  - stsci_sphinx_theme
  - sphinxcontrib-programoutput
  - stginga
  - stistools
  - stsci.convolve
  - stsci.distutils
  - stsci.image
  - stsci.imagemanip
  - stsci.ndimage
  - stsci.numdisplay
  - stsci.skypac
  - stsci.sphere
  - stsci.sphinxext
  - stsci.stimage
  - stwcs
  - synphot
  - stsynphot
  - wcstools
  - webbpsf-data
  - webbpsf
  - wfc3tools
  - wfpc2tools
  - xpa

