# Recipe repository
repository: 'https://github.com/astroconda/astroconda-contrib'
git_ref_spec: 'master'

# Publication channel to consult when determining what packages already exist.
channel_URL: 'http://ssb.stsci.edu/astroconda'

# publication_root path needs to be visible from the slave nodes.
publication_root: '/eng/ssb/websites/ssbpublic/astroconda-j-pub-staging'
packages:
  - asdf
